- .github/workflows/go.yml
- .gitignore
- integration/nwo/fabric/network/network_support.go
This PR brings:
- path fix for git CI failure
- updating .gitignore
> Continuous Integration Enablement #1

- platform/fabric/core/generic/chaincode/discovery.go
- platform/fabric/core/generic/chaincode/invoke.go
- platform/fabric/core/generic/ordering/client.go
- platform/fabric/core/generic/ordering/ordering.go
- platform/fabric/core/generic/peer/common/broadcastclient.go
- platform/fabric/core/generic/peer/common/mockclient.go
- platform/fabric/core/generic/peer/common/ordererclient.go
- platform/fabric/core/generic/peer/common/peerclient.go
- platform/fabric/core/generic/peer/peer.go
- platform/view/core/manager/context.go
- platform/view/services/grpc/client.go
TODO: improve by providing grpc connection pool
> Close GRPC connections from peer & orderer clients

- CODE_OF_CONDUCT.md
- SECURITY.md
> add SECURITY.md and CODE_OF_CONDUCT.md #17

- README.md
- docs/design.md
- integration/fabric/atsa/README.md
- integration/fsc/pingpong/README.md
> additional documentation

- platform/fabric/core/generic/channel.go
- platform/fabric/core/generic/committer/committer.go
- platform/fabric/core/generic/delivery/delivery.go
- platform/fabric/core/generic/txconfig.go
> Restart from genesis if the last transaction committed is a config transaction #4

- platform/fabric/services/state/sbe.go
- platform/view/api/mock/sig_service.go
- platform/view/api/sigservice.go
- platform/view/core/id/mock/sig_service.go
- platform/view/core/id/provider.go
- platform/view/core/sig/service.go
- platform/view/sig.go
> Remove SigService IdentityType #31

- README.md
> adding link to github discussion

- go.mod
- go.sum
- platform/fabric/core/generic/id/info_test.go
- platform/fabric/core/generic/msp/idemix/idemix_test.go
- platform/fabric/core/generic/msp/service_test.go
- platform/fabric/core/generic/vault/txidstore/simpletxidstore_test.go
- platform/fabric/core/generic/vault/vault_test.go
- platform/view/sdk/sdk.go
- platform/view/services/db/db.go
- platform/view/services/db/driver/badger/driver.go
- platform/view/services/db/driver/driver.go
- platform/view/services/db/driver/memory/db.go
- platform/view/services/db/driver/memory/db_test.go
- platform/view/services/db/driver/memory/driver.go
- platform/view/services/db/driver/unversioned/unversioned_test.go
- platform/view/services/kvs/kvs_test.go
> ViewSDK: DB Driver Pluggability #30

- platform/fabric/services/state/namespace.go
- platform/fabric/services/state/recipients.go
- platform/fabric/services/state/stream.go
- platform/view/services/assert/assert.go
> more documentation and comments

- integration/fabric/atsa/chaincode/views/seller.go
- platform/fabric/core/provider.go
- platform/fabric/driver/fns.go
- platform/fabric/fns.go
- platform/fabric/sdk/sdk.go
- platform/fabric/services/endorser/endorsement.go
- platform/fabric/services/endorser/finality.go
- platform/fabric/services/endorser/ordering.go
- platform/fabric/services/state/finality.go
- platform/fabric/services/state/helpers.go
- platform/fabric/services/state/recipients.go
- platform/view/core/endpoint/endpoint.go
- [x ] fabric-sdk: refactor FNS methods
> Support for multiple Fabric Networks #9

- platform/fabric/core/generic/channel.go
- platform/fabric/core/generic/committer.go
- platform/fabric/core/generic/committer/committer.go
- platform/fabric/core/generic/committer/config.go
- platform/fabric/core/generic/committer/driver/driver.go
- platform/fabric/core/generic/committer/endorsertx.go
- platform/fabric/core/generic/delivery/delivery.go
- platform/fabric/core/generic/ledger.go
- platform/fabric/core/generic/txconfig.go
- platform/fabric/core/generic/vault/vault.go
- platform/fabric/core/generic/vault/vault_test.go
- platform/fabric/driver/committer.go
- platform/fabric/driver/ledger.go
- platform/fabric/driver/rwset.go
- platform/fabric/driver/vault.go
- platform/fabric/ledger.go
- platform/fabric/vault.go
with that in the vault before committing 
> committer: match the results of the transaction #63

- integration/fabric/atsa/fsc/views/agree.go
- integration/fabric/atsa/fsc/views/issue.go
- integration/fabric/atsa/fsc/views/transfer.go
- integration/fabric/iou/views/lender.go
- integration/integration.go
- integration/nwo/api/api.go
- integration/nwo/common/context/context.go
- platform/fabric/fns.go
> compatibility requirements with the fabric token sdk #65

- platform/fabric/core/generic/channel.go
- platform/fabric/core/generic/committer.go
- platform/fabric/core/generic/committer/committer.go
- platform/fabric/core/generic/committer/config.go
- platform/fabric/core/generic/committer/endorsertx.go
- platform/fabric/core/generic/transaction/envelope.go
- platform/fabric/driver/ledger.go
> committer: fetch each transaction singularly if the block is too big #67

- .github/workflows/go.yml
> Resurrect go.yml and direct it to merge only

- integration/nwo/fsc/node/node.go
> nwo: make RegisterResponder use import aliasing #73

- platform/fabric/core/generic/transaction/manager.go
- platform/fabric/core/generic/transaction/transasction.go
> fabric/core/generic driver: transaction's network not set properly #79

- platform/view/core/manager/context.go
- platform/view/core/manager/manager.go
- platform/view/core/manager/wrapper.go
- platform/view/view/context.go
> view context: run a view with options #83

- platform/view/core/manager/context.go
- platform/view/core/manager/manager.go
- platform/view/core/manager/wrapper.go
- platform/view/view/context.go
cache context default session #86
view context enhancement #85
> addressing #85 and #86

- .github/workflows/atsacc.yml
- .github/workflows/atsafsc.yml
- .github/workflows/iou.yml
- .github/workflows/pingpong.yml
- .github/workflows/stoprestart.yml
- .github/workflows/twonets.yml
> Only run UTs in UT job

- platform/fabric/core/config.go
> allow multiple fabric networks to set as default #89

- integration/fabric/twonets/topology.go
- integration/nwo/fabric/network/network_support.go
- integration/nwo/fabric/opts/opts.go
- integration/nwo/fabric/topology.go
- integration/nwo/fabric/topology/ds.go
- sampleconfig/topology/fabric_atsa_chaincode.yaml
- sampleconfig/topology/fabric_twonets.yaml
> nwo: set default fabric network per FSC node #91

- platform/view/services/kvs/kvs.go
- platform/view/services/kvs/kvs_test.go
> kvs: support delete #97

- integration/fabric/weaver/relay/topology.go
> Remove Alice from network beta and Bob from network alpha

- go.mod
- go.sum
- platform/fabric/services/weaver/relay/fabric/query.go
> weaver integration: address generation failure #113

- integration/fabric/atsa/fsc/topology.go
- integration/fabric/atsa/fsc/views/agree.go
- integration/fabric/atsa/fsc/views/transfer.go
- integration/nwo/fabric/topology.go
- platform/fabric/services/state/transaction.go
> Extend ATSA/FSC to support anonymous identity

- go.mod
- go.sum
- platform/fabric/core/generic/chaincode/invoke.go
- platform/fabric/core/generic/chaincode/support.go
- platform/fabric/core/generic/network.go
- platform/fabric/core/generic/ordering/ordering.go
- platform/fabric/core/generic/transaction/manager.go
- platform/fabric/core/generic/transaction/transasction.go
- platform/fabric/driver/fns.go
- platform/fabric/driver/sig.go
- platform/fabric/fns.go
- platform/fabric/services/endorser/endorsement.go
- platform/fabric/services/endorser/transaction.go
- platform/fabric/services/weaver/relay/fabric/query.go
- platform/fabric/sig.go
> Use MSPManager to get verifiers #120

- go.mod
- go.sum
- platform/fabric/services/state/cc/query/go.mod
- platform/fabric/services/state/cc/query/go.sum
> fix module name in cc/query

- integration/nwo/fabric/fpc/fpc.go
> NWO: Fabric-FPC, more general root path finder

- platform/view/services/db/keys/utils.go
- platform/view/services/db/keys/utils_test.go
> vault fails to validate keys containing string(utf8.MaxRune) #144

- go.mod
- go.sum
- platform/view/core/manager/context.go
- platform/view/core/manager/deps.go
- platform/view/core/manager/manager.go
- platform/view/core/manager/mock/comm_layer.go
- platform/view/core/manager/mock/session_factory.go
- platform/view/core/manager/wrapper.go
- platform/view/services/comm/comm.go
- platform/view/services/comm/master.go
- platform/view/services/view/view.go
> cleanup context after responding

- platform/fabric/chaincode.go
- platform/fabric/services/fpc/contract.go
> use same tx-id for fpc backend

- go.mod
- go.sum
- integration/fabric/atsa/chaincode/atsa_test.go
- integration/fabric/atsa/fsc/atsa_test.go
- integration/fabric/fpc/echo/echo_test.go
- integration/fabric/iou/iou_test.go
- integration/fabric/stoprestart/stoprestart_test.go
- integration/fabric/twonets/twonets_test.go
- integration/fabric/weaver/relay/realy_test.go
- integration/fsc/pingpong/pingpong_test.go
- integration/fsc/stoprestart/stoprestart_test.go
- integration/integration.go
- integration/nwo/cmd/artifactgen/gen.go
- integration/nwo/common/builder.go
- platform/fabric/core/generic/channel.go
- platform/fabric/core/generic/committer/committer.go
- platform/fabric/core/generic/delivery.go
- platform/fabric/core/generic/delivery/delivery.go
- platform/view/services/comm/p2p.go
- platform/view/services/kvs/kvs.go
- race detection
- committer retries
- concurrency improvements
> improvements

- integration/fsc/pingpong/pingpong_test.go
- integration/integration.go
- integration/nwo/common/context/context.go
- integration/nwo/fabric/fabric.go
- integration/nwo/fabric/network/network_support.go
- integration/nwo/fsc/fsc.go
- platform/view/core/endpoint/endpoint.go
> nwo: improved fabric network support

- integration/integration.go
> Export Infrastructure fields

- platform/fabric/core/generic/network.go
- platform/fabric/core/generic/peer/common/conn.go
- platform/fabric/core/generic/peer/common/peerclient.go
- platform/view/services/client/view/client.go
> Cache peer connections when invoking chaincode/discovery

- platform/fabric/core/generic/network.go
- platform/fabric/core/generic/peer/common/conn.go
- platform/fabric/core/generic/peer/common/peerclient.go
- platform/view/services/client/view/client.go
Reverts hyperledger-labs/fabric-smart-client#187
> Revert "Revert "Cache peer connections when invoking chaincode/discovery""

- integration/nwo/fabric/fabric.go
> Export Platform

- integration/nwo/fabric/topology/configtx_template.go
> Increase default batch size

- integration/nwo/nwo.go
> Add command to kill FSC nodes

- platform/fabric/core/generic/ordering/client.go
- platform/fabric/core/generic/ordering/ordering.go
> FlowControlBroadcast

- platform/fabric/core/generic/ordering/ordering.go
> fix deadlock

- platform/fabric/core/generic/ordering/client.go
> Do not closeSend

- platform/fabric/core/generic/ordering/ordering.go
> Lock when sending

- integration/nwo/fsc/fsc.go
- integration/nwo/fsc/topology.go
> Add option to redirect FSC to file

- .github/workflows/UT.yml
- .github/workflows/atsacc.yml
- .github/workflows/atsafsc.yml
- .github/workflows/fabric-stoprestart.yml
- .github/workflows/fpc-echo.yml
- .github/workflows/go.yml
- .github/workflows/iou.yml
- .github/workflows/pingpong.yml
- .github/workflows/stoprestart.yml
- .github/workflows/twonets.yml
- .github/workflows/weaver-relay.yml
- go.mod
- go.sum
> Maybe fix CI

- .github/workflows/UT.yml
- .github/workflows/atsacc.yml
- .github/workflows/atsafsc.yml
- .github/workflows/fabric-stoprestart.yml
- .github/workflows/fpc-echo.yml
- .github/workflows/go.yml
- .github/workflows/iou.yml
- .github/workflows/pingpong.yml
- .github/workflows/stoprestart.yml
- .github/workflows/twonets.yml
- .github/workflows/weaver-relay.yml
- go.mod
- go.sum
- platform/fabric/core/generic/channel.go
- platform/fabric/core/generic/committer.go
- platform/fabric/core/generic/committer/committer.go
- platform/fabric/core/generic/committer/config.go
- platform/fabric/core/generic/committer/endorsertx.go
- platform/fabric/core/generic/delivery.go
- platform/fabric/core/generic/delivery/deliverclient.go
- platform/fabric/core/generic/delivery/delivery.go
- platform/fabric/core/generic/finality/fabric.go
- platform/fabric/core/generic/txconfig.go
- platform/fabric/driver/committer.go
> Do not use QSCC to query block, fetch it from peer instead

- cmd/fsccli/main_test.go
- cmd/fsccli/testdata/fabric_iou.yaml
- integration/nwo/fabric/network/network_support.go
- integration/nwo/fabric/topology/topology.go
> Redirect OSN output to file

- go.mod
- go.sum
> mod update

- Makefile
- integration/nwo/fabric/fabric.go
> Remove unused docker images

- platform/fabric/core/generic/finality/fabric.go
> Remove stack debug from info logger

- go.mod
- go.sum
- integration/fabric/atsa/chaincode/views/seller.go
- platform/fabric/chaincode.go
- platform/fabric/core/generic/chaincode/discovery.go
- platform/fabric/core/generic/chaincode/invoke.go
- platform/fabric/core/generic/chaincode/support.go
- platform/fabric/core/generic/channel.go
- platform/fabric/core/generic/committer/committer.go
- platform/fabric/core/generic/delivery/deliverclient.go
- platform/fabric/core/generic/delivery/delivery.go
- platform/fabric/core/generic/finality/fabric.go
- platform/fabric/core/generic/ledger.go
- platform/fabric/core/generic/network.go
- platform/fabric/core/generic/ordering/ordering.go
- platform/fabric/core/generic/peer/common/conn.go
- platform/fabric/core/generic/peer/common/peerclient.go
- platform/fabric/core/generic/peer/peer.go
- platform/fabric/driver/chaincode.go
- platform/fabric/driver/channel.go
> peer load balancing

- integration/nwo/fabric/network/resolver.go
- integration/nwo/fsc/fsc.go
- integration/nwo/fsc/node/core_template.go
- integration/nwo/fsc/resolver.go
- platform/fabric/core/generic/finality/fabric.go
- platform/fabric/core/generic/finality/finality.go
- platform/fabric/core/generic/finality/view.go
- platform/fabric/core/generic/finality/views.go
- platform/fabric/core/generic/msp/service.go
- platform/fabric/core/provider.go
- platform/fabric/core/views/finality.go
- platform/view/core/endpoint/endpoint.go
- platform/view/core/endpoint/resolver.go
- platform/view/sdk/sdk.go
- samples/fabric/iou/topology/topology.go
> streanline connection ports

- go.mod
- go.sum
- platform/view/services/id/ecdsa/ecdsa.go
> FSC identity, use ecdsa with low s #226

- platform/fabric/core/generic/msp/service.go
> Data race on RegisterIdemixMSP #232

- integration/nwo/fabric/topology/fpc.go
> Ability to specify the organizations on which to install a FPC

- Makefile
- platform/fabric/chaincode.go
- samples/README.md
- samples/fabric/iou/README.md
- samples/fabric/weaver/relay/README.md
- samples/fabric/weaver/relay/chaincode/storage.go
- samples/fabric/weaver/relay/relay.go
- samples/fabric/weaver/relay/topology/topology.go
- samples/fabric/weaver/relay/views/local.go
- samples/fabric/weaver/relay/views/remote.go
> weaver relay f2f sample

- integration/nwo/fabric/topology/core_template.go
- integration/nwo/fabric/topology/ds.go
- platform/fabric/core/generic/config/config.go
- platform/fabric/core/generic/config/ds.go
- platform/fabric/core/generic/msp/idemix/provider.go
- platform/fabric/core/generic/msp/service.go
- platform/fabric/core/provider.go
- platform/view/services/kvs/kvs.go
> add ability to configure idemix cash size #243

- platform/view/services/assert/retry.go
- platform/view/services/comm/p2p_test.go
> fix p2p unit-tests flake #246

- platform/fabric/core/generic/finality/fabric.go
- platform/view/core/manager/context.go
- platform/view/core/manager/wrapper.go
- platform/view/core/sig/service.go
- platform/view/services/server/view/impl.go
> remove debug.Stack logging where not needed

- platform/view/core/sig/service.go
> streamline sig service logs

- integration/nwo/cmd/network/cmd.go
> call StartCMDPostNew also for the Generate command

- samples/README.md
Signed-off-by: Andrei Lebedev <lebdron@gmail.com>
> Add a note on disabling the logger or modifying its configuration

- README.md
Signed-off-by: Rajat Sharma <connecttorajat@outlook.com>
> Documentation for FTS_PATH changed as copy paste won't work

- integration/nwo/fabric/topology/core_template.go
- platform/fabric/core/generic/channel.go
- platform/fabric/core/generic/config/config.go
> fabric-sdk: add keep alive config support #279

- .gitignore
- platform/view/core/sig/deserializer.go
Signed-off-by: Mathilde Ffrench <mathilde.ffrench@fr.ibm.com>
> Fix sig deserializer data race

- platform/view/services/db/keys/utils.go
Signed-off-by: Saoussen MAROUANI <saoussen.marouani@ibm.com>
> increase namespace length limit to 128 #285

- platform/view/services/db/driver/memory/db.go
see ticket https://github.com/hyperledger-labs/fabric-smart-client/issues/276
Signed-off-by: Mathilde Ffrench <mathilde.ffrench@fr.ibm.com>
> fix db memory data race

- platform/fabric/core/generic/config/config.go
- platform/fabric/core/generic/msp/service.go
- platform/fabric/core/provider.go
Signed-off-by: Mathilde Ffrench <mathilde.ffrench@fr.ibm.com>
> Improve identity cache default

- platform/fabric/core/generic/ledger.go
- platform/fabric/core/generic/vault/rwset.go
- platform/fabric/core/generic/vault/vault.go
- platform/fabric/core/generic/vault/vault_test.go
- platform/fabric/driver/vault.go
- platform/fabric/vault.go
> improve GetEphemeralRWSet with namespaces as input #275

- integration/nwo/fabric/network/resolver.go
- platform/fabric/chaincode.go
- platform/fabric/core/generic/chaincode/discovery.go
- platform/fabric/core/generic/chaincode/invoke.go
- platform/fabric/driver/chaincode.go
- platform/fabric/services/state/certification.go
This enhancement is tested here: https://github.com/hyperledger-labs/fabric-token-sdk/pull/260
> extract IPs from discovery #293

- README.md
- integration/nwo/fsc/fsc.go
- Update readme with link to gopath doc
- Enforce GOPATH is set when using integration test suite
> Enforce GOPATH

- Makefile
- docs/view-sdk.md
- docs/view/api.md
- go.mod
- go.sum
- integration/fsc/pingpong/cmd/responder/main.go
- integration/fsc/pingpong/topology.go
- node/node.go
- pkg/api/registry.go
- pkg/node/node.go
- platform/view/core/manager/manager.go
- platform/view/core/manager/manager_test.go
- platform/view/driver/flowregistry.go
- platform/view/registry.go
> RegisterResponder function needs to have two views that should be sent from two different applications #301

- integration/nwo/fabric/network/network_support.go
- integration/nwo/fabric/network/utils.go
> Add NWO support for existing fabric bins

- integration/nwo/cmd/cryptogen/cryptogen.go
- integration/nwo/fabric/packager/ccmetadata/validators.go
- integration/nwo/fabric/packager/golang/platform.go
- platform/view/core/config/viper/config_util.go
> Reduce staticcheck warnings (ST1005)

- platform/fabric/core/generic/msp/cache.go
- Applying changes from https://github.com/hyperledger-labs/fabric-token-sdk/pull/304
> Optimize msp cache

- integration/nwo/fabric/fpc/fpc.go
- integration/nwo/monitoring/hle/hle.go
- integration/nwo/monitoring/monitoring/monitoring.go
- platform/fabric/core/generic/msp/idemix/deserializer.go
- platform/fabric/core/generic/msp/idemix/id.go
- platform/fabric/core/generic/msp/service.go
- platform/fabric/core/generic/transaction/proposal.go
- platform/orion/core/generic/vault.go
- platform/view/services/events/simple/eventbus.go
- platform/view/services/kvs/kvs.go
* ST1019: imported more than once
> Reduce staticcheck warnings (ST1019, S1023)

- platform/fabric/services/state/vault.go
- platform/fabric/services/state/vault/vault.go
- platform/view/services/kvs/keys.go
- platform/view/services/kvs/kvs.go
- platform/view/services/kvs/kvs_test.go
- Return the key when iterating 
- Add support function for splitting keys
> KVS extensions

- MAINTAINERS.md
> Add mbrandenburger to maintainers

- platform/fabric/services/chaincode/endorse.go
- platform/fabric/services/chaincode/query.go
This reverts commit f7131b6e5448d2b77ab3aba23ab175e80a97c93b.
> Revert "Reduce staticcheck warnings (SA4023) (#344)"

- integration/nwo/fabric/platform.go
> Reduce staticcheck warnings (SA4004)

- samples/fabric/iou/.gitignore
- samples/fabric/weaver/relay/.gitignore
> Adding .gitignore to samples

- docs/fabric-sdk.md
- integration/nwo/fabric/topology/core_template.go
- platform/fabric/core/generic/config/config.go
- platform/fabric/core/generic/ordering/ordering.go
- platform/orion/core/generic/config/config.go
> fabric-sdk: cleanup ordering connection on failure + retry #377

- .github/workflows/tests.yml
- Makefile
- ci/scripts/install_softhsm.sh
- ci/scripts/setup_softhsm.sh
Signed-off-by: sapthasurendran <saptha.surendran@ibm.com>
Updated softhsm setup script to add support for mac
> hsm support for mac

- platform/view/core/endpoint/endpoint.go
- platform/view/services/comm/io/conn_test.go
- platform/view/services/comm/p2p.go
- platform/view/services/comm/p2p_test.go
- platform/view/services/comm/session.go
> view comm layer: override ip address #389

- platform/fabric/core/generic/msp/service.go
> if no default MSP is set, pick the first

- samples/README.md
> commit to go1.18

- pkg/node/node.go
closes #406
Signed-off-by: Dave Kelsey <d_kelsey@uk.ibm.com>
> Fix npe if no core file found

- .github/workflows/tests.yml
- .gitignore
- Makefile
- README.md
- ci/scripts/download_fabric.sh
- go.mod
- go.sum
- integration/nwo/fabric/network/components.go
- integration/nwo/fabric/network/network_support.go
- platform/fabric/core/generic/chaincode/discovery.go
- platform/view/services/metrics/operations/system.go
- samples/README.md
- samples/fabric/iou/README.md
- samples/fabric/weaver/relay/README.md
follow-on from #423 as merge mess meant I needed to open a new PR
Signed-off-by: Dave Kelsey <d_kelsey@uk.ibm.com>
> NWO to only use Fabric Binaries

- integration/orion/cars/views/transfer.go
- platform/orion/core/generic/session.go
- platform/orion/driver/sm.go
- platform/orion/services/db/orion.go
- platform/orion/services/otx/loaded.go
- platform/orion/transaction.go
> keys are sanitised directly by orion, no need for extra sanitization

- platform/view/services/db/driver/badger/badger.go
- platform/view/services/db/driver/memory/db.go
> view db: delete the key if the value is set to nil

- integration/integration.go
- integration/nwo/fabric/topology/core_template.go
- integration/nwo/fsc/fsc.go
- integration/nwo/fsc/node/core_template.go
- integration/nwo/fsc/resolver.go
- integration/nwo/fsc/templates.go
- integration/nwo/fsc/topology.go
- platform/view/core/endpoint/endpoint.go
> Changes in templates for re-usability of NWO

- integration/fsc/pingpong/pingpong_test.go
- integration/nwo/client/web.go
- platform/view/services/client/web/client.go
- platform/view/services/client/web/wsclient.go
- platform/view/services/server/web/handler.go
Websocket client, small fixes for server and unit test
> Support for websockets

- integration/nwo/fabric/topology/core_template.go
- platform/fabric/core/generic/id/info_test.go
- platform/fabric/core/generic/msp/idemix/deserializer.go
- platform/fabric/core/generic/msp/idemix/idemix.go
- platform/fabric/core/generic/msp/idemix/provider.go
- platform/fabric/core/generic/msp/service.go
- platform/fabric/core/generic/msp/x509/loader.go
- platform/fabric/core/generic/msp/x509/provider.go
- platform/fabric/core/generic/msp/x509/setup.go
- platform/fabric/core/generic/msp/x509/x509_test.go
- platform/view/services/comm/endpoint.go
This PR brings in support for the new idemix and the ability to chose aries as crypto proving.
It improves also on other minors: keystore path and ip parsing.
> Updated dependencies

- docs/core-fabric.md
- platform/fabric/core/generic/chaincode.go
- platform/fabric/core/generic/chaincode/chaincode.go
- platform/fabric/core/generic/chaincode/discovery.go
- platform/fabric/core/generic/chaincode/invoke.go
- platform/fabric/core/generic/channel.go
- platform/fabric/core/generic/committer/committer.go
- platform/fabric/core/generic/config/config.go
- platform/fabric/core/generic/config/ds.go
- platform/fabric/core/generic/delivery.go
- platform/fabric/core/generic/delivery/delivery.go
- platform/fabric/core/generic/delivery/random.go
- platform/fabric/core/generic/finality/fabric.go
- platform/fabric/core/generic/finality/finality.go
- platform/fabric/core/generic/rwset/composite.go
- platform/fabric/core/generic/txconfig.go
- platform/fabric/core/generic/vault.go
This PR has the scope to remove the magic constants and load them from the configuration
> load params from configuration

- integration/nwo/common/builder.go
https://github.com/hyperledger-labs/fabric-smart-client/security/dependabot/89
> remove support for git download

- integration/integration.go
- integration/nwo/nwo.go
This PR allows to run topologies even without FSC nodes, which is very helpful when developing nwo platforms and extensions.
> Allow to start a toplogy without FSC nodes

- Makefile
- integration/nwo/monitoring/hle/docker.go
- samples/fabric/iou/README.md
- samples/fabric/iou/topology/topology.go
- samples/fabric/weaver/relay/README.md
This PR does the following:
- It updates HLE docker images to version 2.0 (https://github.com/hyperledger-labs/blockchain-explorer)
- Updates to the samples
> update HLE and samples

- integration/nwo/api/api.go
- integration/nwo/fsc/cli.go
- platform/view/core/manager/manager.go
- platform/view/sdk/web/service.go
- platform/view/services/client/view/client.go
- platform/view/services/client/web/client.go
Adds support for traces for REST view calls and fixes a context-propagation issue
> Support for traces

- integration/fabric/iou/views/approver.go
- integration/fabric/iou/views/lender.go
- samples/fabric/iou/README.md
- samples/fabric/iou/views/approver.go
- samples/fabric/iou/views/lender.go
This PR fixes the error message returned by some assertions in the IOU sample
> Fix assertion error message

- .github/workflows/tests.yml
- Makefile
- platform/common/utils/lazy/holder.go
- platform/common/utils/lazy/holder_test.go
- platform/fabric/core/generic/chaincode/discovery.go
- platform/fabric/core/generic/chaincode/manager.go
- platform/fabric/events_test.go
- platform/view/services/comm/host/rest/websocket/stream_test.go
- platform/view/services/comm/session.go
- platform/view/services/kvs/kvs_test.go
> enable race unit-tests

- docs/fabric/fabricdev/core/fabricdev/transaction/manager.go
- platform/fabric/chaincode.go
- platform/fabric/core/generic/chaincode/invoke.go
- platform/fabric/core/generic/delivery/service.go
- platform/fabric/core/generic/transaction/id.go
- platform/fabric/core/generic/transaction/manager.go
- platform/fabric/delivery.go
- platform/fabric/driver/chaincode.go
- platform/fabric/driver/delivery.go
- platform/fabric/driver/transaction.go
- platform/fabric/driver/vault.go
- platform/fabric/transaction.go
introduce scan block from to start the scanning of block from a given block num
> fabric: scan block from

- platform/fabric/events_test.go
Before:
```bash
❯ time go test -count=100 -failfast -race ./platform/fabric
--- FAIL: TestEventListener (1.38s)
events_test.go:86: expected channel to be closed
FAIL
FAIL    github.com/hyperledger-labs/fabric-smart-client/platform/fabric 27.400s
FAIL
go test -count=100 -failfast -race ./platform/fabric  2.08s user 1.79s system 13% cpu 29.501 total
```
Now:
```bash
❯ time go test -count=100 -failfast -race ./platform/fabric
ok      github.com/hyperledger-labs/fabric-smart-client/platform/fabric 10.572s
go test -count=100 -failfast -race ./platform/fabric  10.89s user 3.79s system 124% cpu 11.822 total
```
> Fix flaky test

- go.mod
- go.sum
- platform/view/services/metrics/disabled/disabled_suite_test.go
- platform/view/services/metrics/disabled/provider_test.go
- platform/view/services/metrics/internal/namer/namer_suite_test.go
- platform/view/services/metrics/internal/namer/namer_test.go
- platform/view/services/metrics/prometheus/prometheus_suite_test.go
- platform/view/services/metrics/prometheus/provider_test.go
- platform/view/services/metrics/statsd/goruntime/collector_test.go
- platform/view/services/metrics/statsd/goruntime/goruntime_suite_test.go
- platform/view/services/metrics/statsd/provider_test.go
- platform/view/services/metrics/statsd/statsd_suite_test.go
This PR is related to [#828](https://github.com/hyperledger-labs/fabric-smart-client/issues/828)
> Replace ginkgo v1 with v2 everywhere

- go.mod
- go.sum
- platform/fabric/core/generic/committer/event_test.go
- platform/fabric/services/state/namespace_test.go
- platform/view/services/assert/assert.go
- platform/view/services/db/driver/sql/common/helpers.go
- platform/view/services/registry/sp_test.go
- platform/view/services/storage/vault/vaultstore_test.go
This PR is related to https://github.com/hyperledger-labs/fabric-smart-client/issues/828
> consistent use of testify

- integration/nwo/fabric/network/network_support.go
- integration/nwo/fabric/network/utils.go
make function comment match function name
> chore: make function comment match function name

- platform/common/utils/cache/eviction.go
- call onEvict if different from nil
> fixes to make token-sdk working

- integration/fabric/atsa/chaincode/chaincode/asset_transfer.go
https://sonarqube-prod.apps.wdc-sonarqube-prod.core.cirrus.ibm.com/project/issues?impactSeverities=HIGH&impactSoftwareQualities=MAINTAINABILITY&issueStatuses=CONFIRMED%2COPEN&open=7d74802d-b012-447a-8ce3-bda60ecdd212&id=403726-1806983
> Refactor this method to reduce its Cognitive Complexity

- platform/view/services/storage/driver/sql/postgres/test_utils.go
This PR addresses the issue #982
> Fix postgres container health-check

- platform/fabric/core/generic/events/listenermanager.go
This PR adds the possibility to instantiate the fabric-sdk event listener in such a way the events are fired sequentially.
This feature should avoid the glitches seen in the Token-SDK (https://github.com/hyperledger-labs/fabric-token-sdk/pull/1143). Indeed, what happens in the token sdk is the following:
- a listener is used to catch changes to the public parameters
- for each event a go routine is started
- therefore it might happen that a go routine for an event that happened later is processed before the go routine for an event that happened earlier causing misalignment.
> fabric-sdk: sequential events

- docs/core-fabric.md
- integration/nwo/fsc/node/core_template.go
- integration/nwo/fsc/topology.go
- integration/nwo/fsc/topology_test.go
- platform/common/services/logging/config.go
- platform/common/services/logging/logger.go
- platform/common/services/logging/otel.go
- platform/common/services/logging/otel_test.go
- platform/common/services/logging/types.go
- platform/common/services/logging/types_test.go
- platform/view/services/config/provider.go
This PR introduce a configurable mechanism to sanitize Otel events.
> otel: sanitize event strings #1018

- integration/fabric/iou/views/borrower.go
- platform/fabric/driver/id.go
remove redundant words in comment
> chore: remove redundant words in comment

- Makefile
- pkg/utils/errors/errors.go
- platform/view/sdk/dig/sdk.go
- platform/view/sdk/dig/support/endpoint/resolver.go
- platform/view/services/comm/host/rest/provider.go
- platform/view/services/comm/p2p.go
- platform/view/services/comm/service.go
- platform/view/services/endpoint/resolver.go
This PR does the following:
- It adds the p2p port to the resolver for `fsc.id`
- It adds `Join` to the error pacakge.
> extensions
