hyperledger-labs/fabric-smart-client

- integration/fsc/pingpong/README.md
> minor fix to documentation #2

- docs/design.md
- docs/fabric-sdk.md
- docs/view-sdk.md
- integration/fsc/pingpong/README.md
- integration/fsc/pingpong/factory.go
- integration/nwo/fsc/node/node.go
- integration/nwo/fsc/topology.go
- platform/fabric/core/generic/msp/service.go
- platform/view/config.go
- platform/view/driver/config.go
- platform/view/driver/endpointservice.go
- platform/view/driver/flowmanager.go
- platform/view/driver/flowregistry.go
- platform/view/driver/identityprovider.go
- platform/view/driver/session.go
- platform/view/driver/sigservice.go
- platform/view/endpoint.go
- platform/view/identity.go
- platform/view/manager.go
- platform/view/registry.go
- platform/view/sig.go
+ comments to the interfaces and structs of the view sdk
> additional documentation

- integration/README.md
- integration/fabric/iou/README.md
- integration/fabric/iou/views/approver.go
- integration/fabric/iou/views/borrower.go
- integration/fabric/iou/views/lender.go
- platform/fabric/services/state/identities.go
- sampleconfig/topology/fabric_iou.yaml
> iou sample: additional documentation and comments to the code

- integration/nwo/fabric/topology/core_template.go
> Support for multiple Fabric Networks #9

- integration/nwo/fabric/packager/golang/platform.go
use "github." as prefix to identity the modeule root dir rather "github.com".
> go packager: prefix fix

- go.mod
- go.sum
- platform/fabric/core/generic/committer.go
- platform/fabric/core/generic/rwset/processor.go
- platform/fabric/core/generic/vault/interceptor.go
- platform/fabric/core/generic/vault/rwset.go
- platform/fabric/core/generic/vault/vault.go
- compare a rws against an inspector
- does not fail if the rws bytes are different
but rwsets are equal
- todo: extend vault support for Fabric's rws
> vault rws comparison fix

- integration/nwo/common/runner/ginkgomon.go
- integration/nwo/fabric/network/network_support.go
- integration/nwo/fabric/topology/topology.go
to be stored on file. The logs can be found under logs/peers
> EnableLogPeersToFile on Fabric Topology to enable peer's logs

- platform/view/services/grpc/client.go
> Make default KA in CreateGRPCClient zero value

- platform/view/services/grpc/client.go
Reverts hyperledger-labs/fabric-smart-client#199
> Revert "Make default KA in CreateGRPCClient zero value"

- platform/view/services/db/keys/utils.go
Fabric does not set a limit on the length of the keys in a RWSet.
This PR is to match the same constraint.
> larger keys in rw sets

- integration/nwo/fabric/fpc/fpc.go
- integration/nwo/fabric/topology/chaincode.go
- integration/nwo/fabric/topology/fpc.go
DCAP based attestation requires to attach the /dev/sgx/provision device
to the FPC docker container. This commit allows to attach multiple
devices to the container. The user is responsible to detect the devices
and provide them via the WithSGXDevicesPaths option.
> Attach SGX devices to FPC container

- platform/view/services/kvs/kvs.go
This PR addresses a bug in the KVS, where a RLock release is called on a unlocked lock.
> Remove wrong rlock release

- samples/README.md
Signed-off-by: sapthasurendran <saptha.surendran@ibm.com>
Updated go version from 1.16 to 1.17 in the readme file.
> Changed go version requirement in README

- integration/fabric/iou/iou_test.go
- integration/nwo/fabric/topology/core_template.go
- platform/fabric/core/generic/network.go
- platform/fabric/core/generic/txconfig.go
Currently, the FSC node uses only the orderers defined
in the configuration file. But, orderers can change
with a configuration update.
Thefore, this PR let the fabric-sdk to use the orderers
defined in the configuration block.
> fabric-sdk: use orderers set in the config block

- platform/fabric/core/generic/network.go
- platform/fabric/core/generic/ordering/ordering.go
- platform/fabric/core/generic/txconfig.go
- platform/fabric/core/provider.go
- platform/view/core/manager/manager.go
- platform/view/driver/flowregistry.go
- platform/view/registry.go
This PR introduces utility functions needed to address https://github.com/hyperledger-labs/fabric-token-sdk/issues/283 
Enhancements:
- add ability to retrive responder from the registry
- additional logging
Bug fix:
- fabric-sdk: update orderers list when apply config blocks after a restart
> view-sdk: enhancements 

- integration/nwo/fabric/fpc/connections.go
- integration/nwo/fabric/fpc/fpc.go
In order to use FSC NWO to setup and run a stand-alone Fabric
network, applications based on the Fabric Client SDK require a
connection file to connect to the network. This commit introduces
the generation of such connection profiles.
Currently, it enabled with FPC only but can later extended.
> Generate connection.yaml

- platform/fabric/core/generic/committer/committer.go
- platform/fabric/core/generic/msp/cache.go
- platform/fabric/services/endorser/endorsement.go
- platform/fabric/services/state/flow.go
- platform/fabric/services/state/recipients.go
- platform/fabric/services/state/transaction.go
- platform/orion/core/generic/committer/committer.go
- platform/view/services/id/ecdsa/view.go
- platform/view/services/session/json.go
- platform/view/services/session/session.go
Using time.After enqueues an entry in Go's runtime scheduler and doesn't garbage collect it even if the function the timer was fired from terminates.
As a result, there can be a temporary high memory pressure and it degrades performance.
Replaced all places where time.After was used except in places that are used as samples or tests.
> Use time.NewTimer instead of time.After

- platform/fabric/core/generic/rwset/envelope.go
- platform/fabric/core/generic/rwset/processor.go
- platform/fabric/core/generic/transaction/envelope.go
- platform/fabric/core/generic/transaction/pr.go
- platform/view/services/comm/p2p.go
As part of issue #174, replaced most dependencies of gogo/protobuf/proto with golang/protobuf/proto. The remaining occurrences reside in p2p.go and their removal requires handling of the dependency from the package gogo/protobuf/io.
> Removed simple gogo/protobuf/proto dependencies

- integration/fabric/atsa/chaincode/chaincode/asset_transfer.go
- integration/fabric/atsa/chaincode/chaincode/asset_transfer_queries.go
- platform/fabric/core/generic/delivery/deliverclient.go
- platform/view/services/client/view/client.go
- platform/view/services/flogging/global.go
- platform/view/services/server/view/marshal.go
* SA1019: removed deprecated grpclog.SetLogger and ptypes
> Reduce staticcheck warnings (SA1019)

- integration/nwo/fabric/network/deploy.go
- integration/nwo/fabric/network/network_support.go
- staticcheck.conf
* ST1001: should not use dot imports (excluded assertion-related packages)
> Reduce staticcheck warnings (ST1001)

- platform/fabric/sdk/sdk.go
- platform/orion/sdk/sdk.go
- platform/view/sdk/sdk.go
- platform/view/services/comm/io/msgconn.go
* S1000: removed redundant single-case selects for channels
> Reduce staticcheck warnings (S1000)

- integration/nwo/common/json.go
- platform/view/services/assert/assert.go
* S1034: removed redundant assertions in switch statements
> Reduce staticcheck warnings (S1034)

- integration/nwo/fsc/fsc.go
- integration/nwo/weaver/interopcc.go
- platform/fabric/core/generic/msp/x509/deserializer.go
- platform/fabric/core/generic/ordering/client.go
- platform/fabric/services/endorser/endorsement.go
* S1039: removed unnecessary formatting
> Reduce staticcheck warnings (S1039)

- platform/fabric/core/generic/transaction/transasction.go
- platform/fabric/services/state/certification.go
- platform/fabric/services/state/tags.go
* S1011: replaced append loops with varargs
> Reduce staticcheck warnings (S1011)

- platform/fabric/services/chaincode/endorse.go
- platform/fabric/services/chaincode/query.go
* SA4023: replaced unnecessary null checks
> Reduce staticcheck warnings (SA4023)

- integration/integration.go
- integration/nwo/cmd/main.go
- integration/nwo/common/builder.go
- integration/nwo/fabric/fpc/fpc.go
- integration/nwo/weaver/util.go
- platform/fabric/core/generic/delivery/deliverclient.go
* S1021: merge var assignment and declaration
* S1038, S1025: remove redundant sprintf's
* SA4009: remove overwritten assignment
* S1005: removed unnecessary assignment to blank identifier
* SA9003: removed empty branch
> Reduce staticcheck warnings (S1021, S1038, S1025, SA4009, S1005, SA9003)

- Makefile
The main.go under
/integration/fsc/pingpong/cmd/responder
is not generated automatically, hence it should not be cleaned when make clean is invoked
> Remove cleaning of non-generated file

- platform/view/sdk/sdk.go
* SA4006: unused var and function
> Reduce staticcheck warnings (SA4006)

- platform/fabric/core/generic/committer.go
- platform/fabric/core/generic/committer/endorsertx.go
- platform/orion/core/generic/committer/committer.go
- platform/orion/core/generic/vault.go
if a transaction is unknown and is marked as valid by the backend, then there is no need to discard anything from the vault
https://github.com/hyperledger-labs/fabric-token-sdk/pull/335 depends on this PR.
> committer improvements

- .gitignore
- integration/fabric/weaver/relay/relay_test.go
- add integration test generated artifacts to gitignore
- let weaver cleanup testdata folder if test succeeds
> Cleanup integration tests

- integration/fabric/atsa/chaincode/chaincode/asset_transfer.go
As part of issue https://github.com/hyperledger-labs/fabric-smart-client/issues/50, removed warnings related to:
SA9005: missing marshaling mechanism
> Make ATSA Chaincode receipt struct fields public

- checks.mk
Runs staticcheck with `make checks`.
Currently, this is supposed to fail via CI until #50 is resolved.
> Enable staticcheck via make checks

- deps.go
- go.mod
- go.sum
Some of the blank dependencies in deps.go are not needed anymore.
> Cleanup deps.go

- platform/fabric/services/chaincode/query.go
This adds a missing option to select the endorsing peers via MSPIDs when
performing a query. We already have this option for invoke.
> Add WithEndorsersByMSPIDs to query chaincode view

- integration/fabric/fpc/echo/topology.go
- integration/nwo/fabric/network/resolver.go
- integration/nwo/fsc/tracing/aggregator_test.go
- platform/fabric/chaincode.go
- platform/fabric/core/generic/chaincode/invoke.go
- platform/fabric/driver/chaincode.go
- platform/fabric/services/fpc/contract.go
This PR updates NWO to remove from the resolvers references to Fabric peers.
The FPC integration was relaying in these resolvers. To fix this, the PR updates the FPC integration to leverage Fabric Discovery.
In addition, a flaky unit-test has been disabled.
> fabric-sdk: do not add resolvers for Fabric peers

- integration/integration.go
- integration/nwo/fabric/network/checks.go
- integration/nwo/orion/platform.go
- platform/fabric/chaincode.go
- platform/fabric/core/generic/rwset/envelope.go
- platform/fabric/core/generic/transaction/envelope.go
- platform/fabric/driver/transaction.go
- platform/orion/core/generic/transaction/manager.go
- platform/orion/driver/transaction.go
- platform/orion/transaction.go
- NWO, fabric CheckTopologyFSCNodes fails if an FSC node doesn't have an organization
- NWO: skip orion is no role is set
- String function added to Envelope (fabric and orion)
- Improved logs and errors
> minor enhancements

- integration/fabric/iou/views/approver.go
- integration/fabric/iou/views/borrower.go
- integration/fabric/iou/views/utils.go
- integration/nwo/common/runner/runner.go
- integration/nwo/fabric/topology.go
- integration/nwo/nwo.go
- pkg/utils/compose/compose.go
- pkg/utils/compose/compose_test.go
- platform/fabric/core/generic/committer.go
- platform/orion/core/generic/committer/committer.go
- platform/orion/core/generic/network.go
nwo:
- fix stop/start FSC node
fabric:
- if an envelope is stored for the txid, then commit it
orion:
- if an envelope is stored for the txid, then commit it
- finality fix for unknown transactions for which an envelope is stored. 
various:
- fix Committer's lister + integration test
> Various bug fix

- platform/fabric/core/generic/committer/endorsertx.go
Currently, when a transaction is marked is invalid by Fabric and it is unknown to the vault, no event is fired.
The point is that the node can still be aware of the transaction because it stores the corresponding envelope.
This PR, discard all transactions.
> fabric: call discard for unknown tx

- platform/fabric/channel.go
- platform/fabric/core/generic/committer.go
- platform/fabric/core/generic/delivery/delivery.go
- platform/fabric/core/generic/vault/txidstore/simpletxidstore.go
- platform/fabric/core/generic/vault/txidstore/simpletxidstore_test.go
- platform/fabric/core/generic/vault/vault.go
- platform/fabric/core/generic/vault/vault_test.go
- platform/fabric/ledger.go
- platform/fabric/transaction.go
- platform/orion/core/generic/ledger.go
- platform/orion/core/generic/vault/simpletxidstore.go
- platform/orion/core/generic/vault/simpletxidstore_test.go
- platform/orion/core/generic/vault/vault.go
- platform/orion/driver/sm.go
- platform/orion/ledger.go
- platform/orion/session.go
- platform/orion/vault.go
- Fabric: 
- Export Envelope Service
- Export Transaction Validation Code
- TxIDStore stores now also busy transactions
- Restart delivery from the last block seen, if available.
- Orion:
- Ledger Support 
- Export Discard Tx
- TxIDStore stores now also busy transactions
Used by: https://github.com/hyperledger-labs/fabric-token-sdk/pull/406
> Extensions

- integration/fsc/pingpong/pingpong_test.go
- integration/fsc/pingpong/testdata/fsc/nodes/initiator/core.yaml
- integration/fsc/pingpong/testdata/fsc/nodes/responder/core.yaml
- integration/fsc/pingpong/testdata/fsc/nodes/webclient/core.yaml
- integration/nwo/client/web.go
- integration/nwo/fabric/topology/core_template.go
- integration/nwo/fsc/fsc.go
- integration/nwo/fsc/node/core_template.go
- node/node/start.go
- platform/fabric/core/generic/channel.go
- platform/fabric/core/generic/config/config.go
- platform/fabric/core/generic/config/testdata/core.yaml
- platform/fabric/core/generic/ordering/ordering.go
- platform/view/core/endpoint/resolver.go
- platform/view/sdk/sdk.go
- platform/view/services/flogging/logging.go
- platform/view/services/flogging/logging_test.go
1. create a grpc section in core and move appropriate keys to be children
2. sort out tls for fabric-driver section
3. make web client configuration keys match intent
Signed-off-by: Dave Kelsey <d_kelsey@uk.ibm.com>
> restructure fsc and fabric driver core to be more intuitive

- integration/fsc/pingpong/testdata/fsc/crypto-config.yaml
- integration/nwo/fabric/topology/crypto_template.go
- integration/nwo/fsc/node/crypto_template.go
- platform/fabric/core/generic/delivery/delivery.go
- correct a trace point that was incorrect
- update to include 0.0.0.0 in the x509 SAN fields, for the Ubuntu WSL2 distribution the standard x509 certificates fail validation.
Signed-off-by: Matthew B White <whitemat@uk.ibm.com>
> Minor updates

- integration/nwo/fabric/network/network_support.go
- integration/nwo/fabric/platform.go
- integration/nwo/fabric/topology.go
- integration/nwo/fsc/topology.go
- integration/nwo/orion/platform.go
- integration/nwo/orion/topology.go
- pkg/node/node.go
- platform/fabric/core/generic/chaincode/chaincode.go
- platform/fabric/core/generic/chaincode/discovery.go
- platform/fabric/core/generic/chaincode/invoke.go
- platform/fabric/core/generic/channel.go
- platform/fabric/core/generic/committer.go
- platform/fabric/core/generic/delivery.go
- platform/fabric/core/generic/delivery/delivery.go
- platform/fabric/core/generic/network.go
- platform/fabric/core/provider.go
- platform/fabric/driver/committer.go
- platform/fabric/driver/delivery.go
- platform/fabric/sdk/sdk.go
- platform/orion/core/generic/committer/committer.go
- platform/orion/core/generic/delivery/delivery.go
- platform/orion/core/generic/network.go
- platform/orion/core/generic/vault.go
- platform/orion/core/provider.go
- platform/orion/driver/delivery.go
- platform/orion/driver/ons.go
- platform/orion/finality.go
- platform/orion/sdk/sdk.go
- NWO fabric and orion: ability to remove the vault of FSC nodes
- Introduce the `PostStart` interface. PostStart allows a platform to start services after all the other platforms have been started. This feature has been introduce to allow platforms to add hookups in the fabric and orion commit pipelines before the pipelines start. Fabric and Orion commit pipelines are now activated in post-start.
- fabric chaincode: when querying a chiancode, discovery performs now a `peer query` and not an `endorser query`.
- Fabric and Orion Committer: if the status of a transaction is requested, if this transaction does not exist in the vault but its envelope exists, then the envelope is loaded into the vaul.
The changes to the commit pipelines and `PostStart` allow a node to rebuild its vault if the …
> enhancement pack

- platform/fabric/core/generic/vault/rwset.go
- platform/fabric/services/weaver/relay/fabric/rwset.go
- platform/orion/core/generic/vault/rwset.go
Currently, FSC Vault is more restrictive when parsing RW sets imposing rules that Fabric does not actually impose.
This results in panic when transactions with a RW sets containing keys that do not pass the FSC check are committed to Fabric.
This PR fixes this issue by removing the extra checks.
Signed-off-by: Norhan Ali Araba <Norhan.Ali.Araba-CICNetherlands@ibm.com>
> key validation removal

- platform/fabric/core/generic/channel.go
- platform/fabric/core/generic/committer/committer.go
- platform/fabric/core/generic/committer/config.go
- platform/fabric/core/generic/committer/endorsertx.go
- platform/fabric/core/generic/committer/external.go
- platform/fabric/core/generic/delivery/delivery.go
- platform/fabric/core/generic/finality/fabric.go
- platform/fabric/core/generic/txconfig.go
- platform/orion/core/generic/committer/committer.go
> remove as many panic as possible

- integration/nwo/fabric/topology/orderer_template.go
Listen address should be set to 0.0.0.0
> Fixes in orderer yaml template

- integration/nwo/fabric/topology/core_template.go
Not including chaincode address if port is 0. Otherwise, chaincode tries to connect to the peer as a service.
> Changes in core template

- integration/nwo/fabric/topology/core_template.go
- platform/fabric/core/generic/config/config.go
- platform/fabric/core/generic/config/ds.go
- platform/fabric/core/generic/config/ds_test.go
- platform/fabric/core/generic/msp/idemix/cache.go
- platform/fabric/core/generic/txconfig.go
This PR brings the following:
- adjusted cache size in the NWO template
- better logs
- config committer reloads starting from index 0 or 1
- channel.numRetries must be at least 1
> improvements

- platform/fabric/core/generic/committer/committer.go
If the Orderer MSP does not have Endpoints in its channel config, this PR adds a fallback check. Another valid configuration for orderer endpoints is OrdererAddresses in the ChannelConfig, see https://hyperledger-fabric.readthedocs.io/en/latest/config_update.html.
**Orderer addresses.** A list of addresses where clients may invoke the orderer Broadcast and Deliver functions. The peer randomly chooses among these addresses and fails over between them for retrieving blocks.
The OrdererAddresses do not have TLSRootCerts. The code only uses the OrdererAddresses key if there is one OrdererMSP in the channel, so that it can use the root certs from there.
> add fallback option to use OrdererAddresses

- integration/fabric/iou/views/utils.go
- platform/common/core/generic/committer/finality.go
- platform/common/core/generic/vault/vault.go
- platform/common/driver/committer.go
- platform/fabric/channel.go
- platform/fabric/committer.go
- platform/fabric/core/generic/committer/committer.go
- platform/fabric/core/generic/committer/config.go
- platform/fabric/core/generic/committer/endorsertx.go
- platform/fabric/driver/committer.go
- platform/orion/committer.go
- platform/orion/core/generic/committer/committer.go
- platform/orion/core/generic/vault.go
- platform/orion/driver/committer.go
- platform/orion/driver/vault.go
- platform/orion/ons.go
- platform/orion/vault.go
- platform/view/driver/committer.go
This PR does the following: It allows both orion and fabric commit pipeline to process transactions that are unknown but are accepted by the custom filters.
> transaction filter

- integration/fsc/pingpong/topology.go
- integration/nwo/fsc/fsc.go
- integration/nwo/fsc/node/core_template.go
- integration/nwo/fsc/topology.go
- platform/view/sdk/sdk.go
This PR does the following: It fixes the bug reported in #568 .
The integration tests by default have the web server disabled. Only the `pingpong` test uses it.
The web server can be enabled by setting `WebEnabled` to `true` on the fsc topology.
> fix bug web service

- cmd/fsccli/main.go
- integration/nwo/cmd/main.go
- integration/nwo/fabric/network/network_support.go
- integration/nwo/fsc/fsc.go
- node/node.go
- platform/fabric/core/provider.go
- platform/view/core/config/provider.go
Currently, NWO uses the deprecated --logging-level param when invoking the peer cli. This commit replaces this param with FABRIC_LOGGING_SPEC env variable.
> Replace deprecated logging param in nwo

- platform/view/sdk/dig/sdk.go
caused panic if `grpc.enabled: false`.
> check if grpc server is nil before accessing it

- integration/nwo/common/context/context.go
- pkg/utils/errors/errors.go
- pkg/utils/uuid.go
- platform/fabric/services/state/namespace.go
- platform/orion/sdk/dig/sdk.go
- platform/view/core/manager/manager.go
- platform/view/services/comm/comm.go
- platform/view/services/comm/host/libp2p/bandwidthreporter.go
- platform/view/services/comm/host/libp2p/host.go
- platform/view/services/comm/host/libp2p/stream.go
- platform/view/services/comm/host/rest/client.go
- platform/view/services/comm/host/rest/host.go
- platform/view/services/comm/host/rest/routing/idrouter.go
- platform/view/services/comm/host/rest/routing/labelrouter.go
- platform/view/services/comm/host/rest/routing/routing.go
- platform/view/services/comm/host/rest/server.go
- platform/view/services/comm/host/rest/websocket/common.go
- platform/view/services/comm/host/rest/websocket/multiplexed_provider.go
- platform/view/services/comm/io/logger.go
- platform/view/services/comm/io/streamio/reader.go
- platform/view/services/comm/master.go
- platform/view/services/comm/p2p.go
- platform/view/services/comm/session.go
This PR cleanups the contexts, sessions, and streams management by closing and releasing resources when needed.
> dispose context and close sessions

- integration/fabric/events/chaincode/client.go
- integration/fabric/events/chaincode/events_test.go
- integration/fabric/events/chaincode/topology.go
- integration/fabric/events/chaincode/views/multipleEvents.go
- integration/fabric/events/chaincode/views/multipleListeners.go
- platform/fabric/events.go
- platform/fabric/events_test.go
- platform/fabric/services/chaincode/events.go
With multiple subscribers and events, we encountered a race condition where the OnReceive would still try to send when CloseChaincodeEvents had already closed the channel (which causes a panic). This PR adds a unit- and integration test to reproduce it, and a `closing` boolean behind a mutex to prevent it.
> add closing state to prevent send on closed channel panic

- platform/view/core/endpoint/endpoint.go
- platform/view/core/endpoint/endpoint_test.go
- platform/view/sdk/dig/sdk.go
- platform/view/services/comm/host/rest/websocket/stream_test.go
This PR removes a few race conditions and simplifies the constructor for the endpoint service.
> Remove race conditions and simplify endpoint service constructor

- docs/core-fabric.md
- integration/integration.go
- platform/fabric/core/generic/msp/x509/config.go
- platform/fabric/core/generic/msp/x509/pkcs11/disabled.go
- platform/fabric/core/generic/msp/x509/pkcs11/pkcs11.go
- platform/fabric/core/generic/msp/x509/setup.go
The `github.com/hyperledger/fabric/bccsp/pkcs11` dependency is the only reason we need CGO_ENABLED=1 when building an application that imports FSC. It makes things like cross-architecture builds unnecessarily difficult.
This PR makes it so that if you want to use pkcs11, you have to build the binary with `go build -tags pkcs11`. It includes a default implementation that panics if the user configures HSM in a binary that's not built with `pkcs11` as a build tag.
> hide pkcs11 behind a build tag so that fsc is pure go by default

- platform/fabric/services/state/namespace.go
The error handling of rwSet.GetReadAt overrides the original error that results in returning a wrapped nil error.
> Fix error shadowing in fabric state service

- .github/workflows/git.yml
Fixup commits are great!!! In particular for development and PR review, however, it may happen that the fixup commits are not squashed before a PR is merged that results in a "bad" git history on the main branch.
Bad example:
This PR adds a GH action to check the existence of fixup commits and signals a test fail.
> Add GH Action to block merging fixup commits

- pkg/node/node.go
- platform/view/core/manager/manager.go
- platform/view/driver/flowmanager.go
- platform/view/manager.go
for people who don't InitiateView directly but create the view.Context first, this PR creates the opportunity to pass a go context. This is useful for tracing a request through the process.
> add functions to initiate a view context from an existing go context

- .github/workflows/codeql-analysis.yml
This PR addresses the current issue with CodeQL that fails to automatically build the project.
For now we manually build the fsccli, fscnode. and run unit-tests.
> CodeQL manual build

- platform/view/services/db/driver/sql/postgres/notifier.go
This PR catches a nil event that can be dispatched by the db notifier.
> catch nil event

- docs/core-fabric.md
- platform/common/core/generic/vault/db/helpers.go
- platform/view/services/db/dbtest/bench.go
- platform/view/services/db/driver/badger/badger.go
- platform/view/services/db/driver/driver.go
- platform/view/services/db/driver/notifier/persistence.go
- platform/view/services/db/driver/sql/common/base.go
- platform/view/services/db/driver/sql/common/utils.go
- platform/view/services/db/driver/sql/common/versioned.go
- platform/view/services/db/driver/sql/postgres/bench_test.go
- platform/view/services/db/driver/sql/postgres/persistence.go
- platform/view/services/db/driver/sql/postgres/sql_test.go
- platform/view/services/db/driver/sql/postgres/test_utils.go
- platform/view/services/db/driver/sql/postgres/unversioned.go
- platform/view/services/db/driver/sql/postgres/versioned.go
- platform/view/services/db/driver/sql/sqlite/persistence.go
- platform/view/services/db/driver/sql/sqlite/unversioned.go
- platform/view/services/db/driver/sql/sqlite/versioned.go
- platform/view/services/db/driver/unversioned/unversioned.go
Allows for use case specific tuning of database parameters.
```
maxOpenConns: 20  # optional: max open read connections to the database. Defaults to unlimited. See https://go.dev/doc/database/manage-connections.
maxIdleConns: 20  # optional: max idle read connections to the database. Defaults to 2.
maxIdleTime: 30s  # optional: max duration a connection can be idle before it is closed. Defaults to 1 minute.
```
It also exposes a function `Stats(): any` to the database driver. This can be used for debugging or observability in general. In the case of SQL databases, this provides details about the connection pool (see [go docs](https://pkg.go.dev/database/sql#DBStats). For Badger, it returns the metrics for the underlying block cache.
> add configurable maxIdleConns and maxIdleTime for sql databases

- docs/core-fabric.md
- platform/fabric/core/generic/committer/committer.go
- platform/fabric/core/generic/config/service.go
- platform/fabric/core/generic/delivery/delivery.go
- platform/fabric/core/generic/ordering/cft.go
- platform/view/services/grpc/client.go
And set a default for the orderer retryInterval. Before, it defaulted to immediate.
> when reading channel config, skip orderer endpoints which are empty

- platform/fabric/core/generic/channel.go
- platform/fabric/core/generic/channelprovider.go
- platform/fabric/core/generic/committer/committer.go
- platform/fabric/core/generic/delivery/delivery.go
- platform/fabric/core/generic/driver/identity/msp.go
- platform/fabric/core/generic/network.go
- platform/fabric/core/generic/ordering/ordering.go
- platform/fabric/sdk/dig/generic/providers.go
This PR simplify the constructors used to create a new channel. It also replaces certain dependencies with interfaces and not structs.
This PR is tested against FTS in https://github.com/hyperledger-labs/fabric-token-sdk/pull/804
> pass the network driver to the constructor

- platform/fabric/core/generic/finality/listenermanager.go
Reduced number of calls to delivery service when a listener is evicted
> Batch tx fetches from ledger

- platform/fabric/core/generic/delivery/delivery.go
- platform/fabric/core/generic/delivery/service.go
This PR does the following: It decouples the checking of the stop condition from the reading of the blocks from the delivery service that is a blocking operation. This avoids that the reading process gets stuck after the callback notifies to stop.
> fix delivery service

- platform/fabric/core/generic/committer/committer.go
- platform/fabric/core/generic/delivery/delivery.go
- platform/fabric/core/generic/finality/deliveryflm.go
This PR does the following:
1. It reduces logging form Infof to Debugf;
2. It fixes a bug that was preventing an error returned by the callback function to be propagated as expected.
> return error properly

- go.mod
- go.sum
- platform/fabric/core/generic/chaincode/chaincode.go
- platform/fabric/core/generic/chaincode/discovery.go
This PR replaced the third-party cache implementation within the discovery component with our own. This is part of #827
> Replace ttlcache with our own cache

- platform/common/utils/cache/timeout.go
- platform/common/utils/cache/timeout_test.go
Before
```bash
❯ time go test -count=10 -failfast -race ./platform/common/utils/cache/
--- FAIL: TestTimeoutParallel (3.00s)
Error Trace:    timeout_test.go:74
Error:          Not equal: 0 (expected)
!= 97 (actual)
[recovered]
Error Trace:    timeout_test.go:74
Error:          Not equal: 0 (expected)
!= 97 (actual)
goroutine 138 [running]:
testing.tRunner.func1.2({0x1011d4540, 0xc000104f90})
/opt/homebrew/Cellar/go/1.23.6/libexec/src/testing/testing.go:1632 +0x2c4
testing.tRunner.func1()
/opt/homebrew/Cellar/go/1.23.6/libexec/src/testing/testing.go:1635 +0x47c
panic({0x1011d4540?, 0xc000104f90?})
/opt/homebrew/Cellar/go/1.23.6/libexec/src/runtime/panic.go:785 +0x124
github.com/hyperledger-labs/fabric-smart-client/platform/view/services/assert.(*panickier).Errorf(0xc0001f7188, …
```
> Fix flaky cache timeout tests

- platform/view/services/comm/comm_test.go
Websocket connects may be used by multiple goroutines concurrently. This commit adds a test to stress the session handling, open, send, receive, and eventual close.
The test added here triggers the issue reported in #884.
> Add concurrent websocket session test

- platform/common/utils/lazy/iterator.go
- platform/fabric/services/state/transaction.go
- platform/view/core/manager/context.go
- platform/view/core/manager/context_test.go
- platform/view/core/manager/manager.go
- platform/view/core/manager/sessions.go
- platform/view/core/manager/wrapper.go
- platform/view/services/session/json.go
- platform/view/services/view/context.go
- platform/view/view/context.go
When calling `GetSession` we pass the calling view and the party to reach. If the session is opened for the first time, the party is informed about the calling view as well. In a given context, `GetSession` can be called with different calling view, therefore it should be possible to scope the sessions by calling view as well. This allows the developer to open more than one  session to the same party but starting from different calling views.
This behaviour was not currently supported, this PR introduces this behaviour.
> scope sessions by calling view

- go.mod
- platform/view/services/comm/host/rest/websocket/multiplexed_provider.go
- platform/view/services/comm/host/rest/websocket/multiplexed_provider_test.go
- platform/view/services/comm/host/rest/websocket/stream.go
- platform/view/services/comm/host/rest/websocket/stream_test.go
This PR improves the current websocket implementation and fixes the issue report in #884.
- Introduce connects killall to cleanup all goroutines
- Reduce number of goroutines for shovel messages between several layers
- Add testing
> cleanup websockets multiplexing

- docs/monitoring.md
- go.mod
- go.sum
- platform/common/services/logging/logger.go
- platform/common/services/logging/mock.go
- platform/common/services/logging/otel.go
- platform/common/services/logging/types.go
- platform/fabric/services/endorser/endorsement_proposal.go
- platform/view/services/db/driver/sql/common/utils.go
- platform/view/services/db/driver/sql/postgres/conditions.go
- platform/view/services/db/driver/sql/query/common/types.go
- platform/view/services/db/driver/sql/query/cond/condition_test.go
- platform/view/services/db/driver/sql/query/cond/time.go
- platform/view/services/db/driver/sql/sqlite/conditions.go
Instead of using
```
trace.SpanFromContext(ctx).AddEvent(...)
```
we can use the existing loggers to both log and add an event.
```
logger.InfofContext(ctx, ...)
logger.InfowContext(ctx, ...)
```
> Integrate otelzap to combine logging with span events

- go.mod
- go.sum
- platform/fabric/core/generic/msp/service_test.go
This PR is related to https://github.com/hyperledger-labs/fabric-smart-client/issues/828
> Replace itiai10/copy with built-in os.copyFS

- platform/fabric/core/generic/delivery/delivery.go
fixing an issue when sending nil values in channel in `delivery.go`
> fix: send on closed channel in delivery #970

- README.md
- integration/nwo/fsc/fsc.go
This PR addresses #338. NWO currently enforces profiling for every test. This PR let the user decided when to run with profiling enabled via the `FSCNODE_PROFILE=true` env var.
The profiling section in the readme explains how to do that.
> NWO: disable profiling by default

- platform/view/services/view/manager.go
- platform/view/services/view/manager_test.go
Fixing data race in `platform/view/services/view/manager.go`
> fix: get / set current context in manager #969

- integration/nwo/common/runner/runner.go
- platform/common/utils/closer.go
This PR addresses the following verbose logging.
```
IgnoreError: <nil>
IgnoreError: attempt to clear closed buffer 
```
This PR is part of #981
> Tame ignore error logging

- integration/fabric/atsa/chaincode/atsa_test.go
- integration/fabric/atsa/fsc/atsa_test.go
- integration/fabric/events/chaincode/events_test.go
- integration/fabric/iou/iou_test.go
- integration/fabric/iouhsm/iou_test.go
- integration/fabric/stoprestart/stoprestart_test.go
- integration/fsc/pingpong/pingpong_test.go
- integration/fsc/stoprestart/stoprestart_test.go
- integration/integration.go
- integration/nwo/common/builder.go
Somehow the race flag in the nwo builder got lost. 
As a result the race issue reported in #969 was not found.
This PR brings it back.
> NWO: Bring back nwo race detector

- integration/nwo/cmd/network/cmd.go
- integration/nwo/fabric/docker.go
- integration/nwo/monitoring/monitoring/docker.go
This PR is part of the Performance EPIC #787 and introduces minor tweaks on NWO to enhance testing/benchmarking.
- This PR enables prometheus native histograms when started with NWO
- Improves monitoring startup time 
- Typos
- Disables default usage of race detector when using NWO network CMD. The user can enable the race detector when needed via `StartCMDPostNew` injection. For example:
```go
m := cmd.NewMain("Perf network", "0.1")
mainCmd := m.Cmd()
network.StartCMDPostNew = func(infrastructure *integration.Infrastructure) error {
infrastructure.EnableRaceDetector()
return nil
}
```
> NWO minor improvements

- platform/view/services/comm/host/rest/host.go
- platform/view/services/comm/host/rest/websocket/multiplexed_provider.go
- platform/view/services/comm/host/rest/websocket/stream.go
- platform/view/services/comm/host/rest/websocket/stream_test.go
- platform/view/services/comm/ids.go
- platform/view/services/comm/p2p.go
- platform/view/services/comm/session.go
- platform/view/services/view/manager.go
The current stack suffers from high resource utilization (active number of goroutines and increasing memory usage) when invoking views through the p2p comm layer.
This PR tames the resource consumption.
- set reasonable read buffer size
- cleanup subcon when they are closed
- more efficient sessionID computation
- remove delayed subcon close
- remove delayed context deletion after view execution
> Fix comm stack resource consumption
